# Generated by Django 3.2.4 on 2021-07-24 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0004_sells_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sells',
            name='timing',
        ),
        migrations.AddField(
            model_name='sells',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 25)),
        ),
        migrations.AddField(
            model_name='sells',
            name='time',
            field=models.TimeField(default=datetime.time(1, 9, 1, 636032)),
        ),
    ]
