# Generated by Django 3.2.4 on 2021-07-25 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0005_auto_20210725_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sells',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sells',
            name='time',
            field=models.TimeField(default=datetime.time(11, 38, 34, 147875)),
        ),
    ]
