# Generated by Django 3.2.4 on 2021-07-25 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0007_auto_20210725_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 25)),
        ),
        migrations.AddField(
            model_name='stock',
            name='time',
            field=models.TimeField(default=datetime.time(12, 53, 2, 433806)),
        ),
        migrations.AlterField(
            model_name='sells',
            name='time',
            field=models.TimeField(default=datetime.time(12, 53, 2, 432779)),
        ),
    ]
