# Generated by Django 3.2.4 on 2021-07-27 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0009_auto_20210725_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sells',
            name='agent_name',
        ),
        migrations.AlterField(
            model_name='sells',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 27)),
        ),
        migrations.AlterField(
            model_name='sells',
            name='time',
            field=models.TimeField(default=datetime.time(11, 22, 29, 543989)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 27)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='time',
            field=models.TimeField(default=datetime.time(11, 22, 29, 544989)),
        ),
    ]
